infra: sriov git submodule should point to `main`
Main sriov-network-operator branch has moved from `master` to `main`.

Update the `SRIOV_NETWORK_OPERATOR_TARGET_COMMIT` variable accordingly to
fix errors like [1]:

```
+ cd ../sriov-network-operator/
+ git fetch --all
+ git checkout origin/master
error: pathspec 'origin/master' did not match any file(s) known to git
make: *** [Makefile:140: init-git-submodules] Error 1
```

[1] https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-kni_cnf-features-deploy/2148/pull-ci-openshift-kni-cnf-features-deploy-master-e2e-aws-ci-tests/1877360047533592576

Signed-off-by: Andrea Panattoni <apanatto@redhat.com>